# Generated by Django 6.0.7 on 2026-07-27 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
from django.utils.text import slugify


def generate_feature_codes(apps, schema_editor):
    Feature = apps.get_model('app', 'Feature')
    for feature in Feature.objects.filter(Q(code__isnull=True) | Q(code='')):
        feature.code = feature.slug or slugify(feature.name)
        feature.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dashboard_feature_dashboardfeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.UUIDField(db_index=True, help_text='Tenant identifier')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='circle', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('opens_in_new_tab', models.BooleanField(default=False)),
                ('permission_code', models.CharField(blank=True, max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_feature_item',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoleFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.UUIDField(db_index=True, help_text='Tenant identifier')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_role_feature',
                'ordering': ['role__name', 'feature__name'],
            },
        ),
        migrations.CreateModel(
            name='RoleFeatureAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.UUIDField(db_index=True, help_text='Tenant identifier')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_role_feature_action',
                'ordering': ['role__name', 'feature_action__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='feature',
            name='api_base_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feature',
            name='code',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('MENU', 'Menu'), ('PAGE', 'Page'), ('ACTION', 'Action'), ('REPORT', 'Report'), ('DASHBOARD', 'Dashboard'), ('WIDGET', 'Widget'), ('API', 'Api')], default='MENU', max_length=20),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_assignable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FeatureAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.UUIDField(db_index=True, help_text='Tenant identifier')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('http_method', models.CharField(default='POST', max_length=10)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('permission_code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_actions', to='app.feature')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_feature_action',
                'ordering': ['feature__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.UUIDField(db_index=True, help_text='Tenant identifier')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='circle', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_feature_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='app.featurecategory'),
        ),
        migrations.RunPython(generate_feature_codes, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_feature_code_per_tenant'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='app.feature'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.featureitem'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolefeature',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolefeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_features', to='app.feature'),
        ),
        migrations.AddField(
            model_name='rolefeature',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_features', to='app.role'),
        ),
        migrations.AddField(
            model_name='rolefeature',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolefeatureaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolefeatureaction',
            name='feature_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_feature_actions', to='app.featureaction'),
        ),
        migrations.AddField(
            model_name='rolefeatureaction',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_feature_actions', to='app.role'),
        ),
        migrations.AddField(
            model_name='rolefeatureaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='featureaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'feature', 'code'), name='unique_feature_action_code_per_tenant_feature'),
        ),
        migrations.AddConstraint(
            model_name='featurecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_feature_category_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='featurecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_feature_category_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rolefeature',
            constraint=models.UniqueConstraint(fields=('tenant', 'role', 'feature'), name='unique_role_feature_assignment_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rolefeatureaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'role', 'feature_action'), name='unique_role_feature_action_assignment_per_tenant'),
        ),
    ]
