# Generated by Django 6.0.7 on 2026-07-27 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_featureitem_rolefeature_rolefeatureaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='default_layout',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='home_route',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='logo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='theme',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='DashboardBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.UUIDField(db_index=True, help_text='Tenant identifier')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_route', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='app.dashboard')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_dashboard_banner',
                'ordering': ['dashboard__name', 'display_order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'dashboard', 'title'), name='unique_dashboard_banner_title_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='DashboardQuickAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.UUIDField(db_index=True, help_text='Tenant identifier')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_actions', to='app.dashboard')),
                ('feature_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_actions', to='app.featureaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_dashboard_quick_action',
                'ordering': ['dashboard__name', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'dashboard', 'feature_action'), name='unique_dashboard_quick_action_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='DashboardStatisticCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.UUIDField(db_index=True, help_text='Tenant identifier')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('api_endpoint', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('refresh_interval', models.PositiveIntegerField(default=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_cards', to='app.dashboard')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistic_cards', to='app.feature')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_dashboard_statistic_card',
                'ordering': ['dashboard__name', 'display_order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'dashboard', 'title'), name='unique_dashboard_statistic_card_title_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.UUIDField(db_index=True, help_text='Tenant identifier')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=1)),
                ('height', models.PositiveIntegerField(default=1)),
                ('configuration', models.JSONField(default=dict, blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='app.dashboard')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='app.feature')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_dashboard_widget',
                'ordering': ['dashboard__name', 'display_order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'dashboard', 'title'), name='unique_dashboard_widget_title_per_tenant')],
            },
        ),
    ]
