# Generated by Django 6.0.7 on 2026-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dashboard_default_layout_dashboard_home_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfamethod',
            name='authenticator_app',
            field=models.CharField(blank=True, default='Google Authenticator', max_length=255),
        ),
        migrations.AddField(
            model_name='mfamethod',
            name='device_name',
            field=models.CharField(blank=True, default='phone', max_length=255),
        ),
    ]
